// <auto-generated />
using System;
using BusManagement.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906181435_DeleteBus")]
    partial class DeleteBus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusManagement.Server.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("BusNum")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("BusStartedDateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BusId");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.DailyTripInfo", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<decimal>("Average")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("BusNum")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DistanceCoverd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<decimal>("EveningMeterReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EMR");

                    b.Property<int>("MeterId")
                        .HasColumnType("int");

                    b.Property<decimal>("MorningMeterReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MMR");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TripId");

                    b.HasIndex("BusId");

                    b.HasIndex("EmpId");

                    b.HasIndex("MeterId");

                    b.ToTable("DailyTripInfo");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.EmployeeInfo", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpId");

                    b.HasIndex("BusId");

                    b.ToTable("EmployeeInfo");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.FuelInfo", b =>
                {
                    b.Property<int>("FuelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelId"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<decimal>("FuelAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FuelQuentity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefuleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FuelId");

                    b.HasIndex("BusId");

                    b.ToTable("FuelInfo");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.MeterInfo", b =>
                {
                    b.Property<int>("MeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeterId"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("EveningMeterImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EMRImgUrl");

                    b.Property<decimal>("EveningMeterReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EMR");

                    b.Property<string>("MorningMeterImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MMRImgUrl");

                    b.Property<decimal>("MorningMeterReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MMR");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MeterId");

                    b.HasIndex("BusId");

                    b.ToTable("MeterInfo");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.DailyTripInfo", b =>
                {
                    b.HasOne("BusManagement.Server.Entity.Bus", "Bus")
                        .WithMany("DailyTripInfos")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusManagement.Server.Entity.EmployeeInfo", "EmployeeInfo")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusManagement.Server.Entity.MeterInfo", "MeterInfo")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("EmployeeInfo");

                    b.Navigation("MeterInfo");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.EmployeeInfo", b =>
                {
                    b.HasOne("BusManagement.Server.Entity.Bus", "Bus")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.FuelInfo", b =>
                {
                    b.HasOne("BusManagement.Server.Entity.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.MeterInfo", b =>
                {
                    b.HasOne("BusManagement.Server.Entity.Bus", "Bus")
                        .WithMany("MeterInfos")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusManagement.Server.Entity.Bus", b =>
                {
                    b.Navigation("DailyTripInfos");

                    b.Navigation("EmployeeInfos");

                    b.Navigation("MeterInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
